### PR TITLE
Fix faceit elo formatting

### LINKED ISSUE #4: Improve member information formatting
If the steam name is too long, the FACEIT logo will appear with a large gap behind the elo.

image

### PR DESCRIPTION
**Pull request by marcquark**
Fixes #4 by making the 2nd column, the one that contains the Faceit level, take all of the available space. At the same time it prevents the line in the first column from wrapping on whitespace. This results in a clean formatting of the Faceit ELO no matter the length of the steam name.

### CODE REVIEW

**Comment by marcquark** [comment]
Looks like Chrome and FF behave differently - it works fine for me in FF, can u confirm?

**Comment by timonla** [comment]
Yes, it seems to fix it for firefox.

File: src/scripts/team-page/members/content.js [hunk 1]
```diff
@@ -276,66 +276,63 @@ function improveMemberCards() {
...
-        tableBody.appendChild(steamRow);
+        memberCard.appendChild(steamDiv);
     }
 
-
     if (playerInfo.faceitInfo != null) {
         const faceitInfo = playerInfo.faceitInfo;
 
-        const faceitRow = document.createElement("tr");
+        const faceitDiv1 = document.createElement("div");
```
Comment (timonla) [inline src/scripts/team-page/members/content.js:299]: I think the naming is a bit confusing. I'd suggest something like `faceitDiv` with `eloDiv` and `imageDiv` as children.

Comment (marcquark) [reply src/scripts/team-page/members/content.js]: good suggestion, done!

**Comment by marcquark** [comment]
this should be ready to be merged. we should probably also add a version bump, but i'm not sure which files to modify in which to leave untouched. pls advise or commit a version bump yourself before releasing
